// Generated by tools/build_bom_reader.mjs from app/src/e9_rows.js.

/* ── 붙여넣은 표 읽기: 엑셀·시트(TSV), CSV(, ;), 한 줄씩 적은 글 ──
   열 역할(roles)은 열마다 하나: no 번호 · pn 품번(고객·제조사, 여러 열 가능) · type 품목 · desc 품명·사양(여러 열 가능) · size 호칭 · len 길이 · qty · unit · mat · fin */
const BOM_HDR = {
  no: /^(NO\.?|#|ITEM(\s*(NO\.?|#))?|POS(ITION)?\.?|LINE(\s*(NO\.?|#))?|순번|번호|항목|項番|NR\.?|S\/?N|SEQ\.?|BOM\s*(NO\.?|ITEM))$/i,
  pn: /^(P\/?N|PART\s*(NO\.?|NUMBER|#)|CUST(OMER)?\.?\s*(P\/?N|PART\s*(NO\.?|NUMBER|#)?|ITEM\s*(NO\.?|CODE))|MFR\.?\s*(P\/?N|PART\s*(NO\.?|NUMBER|#)?)|MANUFACTURER('?S)?\s*PART(\s*(NO\.?|NUMBER|#))?|MPN|MAT(ERIAL)?\s*(NO\.?|CODE|#)|ITEM\s*(CODE|NUMBER)|품번|부품\s*번호|도번|도면\s*번호|품목\s*코드|자재\s*(코드|번호)|고객\s*품번|제조사\s*품번|品番|部品番号|図番|CODE|TEILE?-?NR\.?|ARTIKEL(-?NR\.?)?)$/i,
  desc: /^(DESC(RIPTION)?\.?|ITEM\s*DESC(RIPTION)?\.?|PART\s*DESC(RIPTION)?\.?|품명|규격|사양|품명\s*[\/·및]?\s*규격|SPEC(IFICATION)?S?\.?|品名|仕様|名称|品名\s*[\/・]?\s*仕様|型式|NAME|PART\s*NAME|ITEM\s*NAME|BEZEICHNUNG|BENENNUNG)$/i,
  type: /^(TYPE|ITEM\s*TYPE|PART\s*TYPE|KIND|CATEGORY|종류|품종|種類|ART)$/i,
  size: /^(SIZE|DIA\.?|DIAMETER|NOM(INAL)?\.?(\s*(SIZE|DIA\.?))?|THREAD(\s*SIZE)?|호칭(\s*경)?|사이즈|나사|크기|呼び(径)?|サイズ|ねじ|GR(Ö|OE)SSE|ABMESSUNG|GEWINDE)$/i,
  len: /^(LENGTH|LEN\.?|LG\.?|L|(LENGTH|L)\s*\((MM|IN|INCH)\)|길이|長さ|L(Ä|AE)NGE)$/i,
  qty: /^(QTY\.?|Q'?TY|QUANTITY|수량|数量|MENGE|ANZAHL|REQ(UIRED)?\.?\s*QTY|ORDER\s*QTY|QTY\s*\(?(EA|PCS)\)?|TOTAL\s*QTY|소요\s*량)$/i,
  unit: /^(UNIT|UOM|U\/M|단위|単位|EINHEIT|ME)$/i,
  mat: /^(MAT(ERIA)?L|MAT'?L|재질|材質|GRADE|등급|강도|WERKSTOFF|MATERIAL\s*\/\s*GRADE)$/i,
  etc: /^(REMARKS?|NOTES?|비고|특기\s*사항|備考|特記(事項)?|BEMERKUNG(EN)?|COMMENTS?|SPEC(IAL)?\s*(NOTE|REQ(UIREMENT)?S?))$/i,   // 비고·NOTE: NACE·충격시험 같은 요구가 여기 적힌다
  fin: /^(FINISH|COATING|SURFACE(\s*TREATMENT)?|표면\s*처리|도금|表面\s*処理|PLATING|OBERFL(Ä|AE)CHE)$/i,
};
const BOM_ROLES = [['', '사용 안 함'], ['no', '번호'], ['pn', '품번 (고객·제조사)'], ['type', '품목'], ['desc', '품명·사양'], ['size', '호칭'], ['len', '길이'], ['qty', '수량'], ['unit', '단위'], ['mat', '재질'], ['fin', '표면처리'], ['etc', '비고 (함께 읽기)']];
const BOM_MULTI = new Set(['desc', 'pn', 'etc']);   // 여러 열에 줄 수 있는 역할
const roleOf = h => Object.keys(BOM_HDR).find(k => BOM_HDR[k].test(String(h).trim().replace(/\s+/g, ' '))) || '';
// 따옴표 안의 줄바꿈·구분자를 지키며 나눈다 (엑셀은 줄바꿈 있는 셀을 "…"로 감싸 복사한다)
function splitDelim(text, d) {
  const rows = []; let row = [], cur = '', q = false, i = 0;
  for (; i < text.length; i++) {
    const ch = text[i];
    if (q) {
      if (ch === '"') { if (text[i + 1] === '"') { cur += '"'; i++; } else q = false; }
      else cur += ch === '\n' ? ' ' : ch;
      continue;
    }
    if (ch === '"' && !cur.trim()) { q = true; cur = ''; continue; }
    if (ch === d) { row.push(cur); cur = ''; continue; }
    if (ch === '\n') { row.push(cur); rows.push(row); row = []; cur = ''; continue; }
    cur += ch;
  }
  row.push(cur); rows.push(row);
  if (q) return null;   // 닫히지 않은 따옴표: 단순 분할로 되돌아간다
  return rows.map(r => r.map(s => s.replace(/\s+/g, ' ').trim())).filter(r => r.some(Boolean));
}
const QTY_RE = /^-?[\d,]+(?:\.\d+)?\s*(EA|PCS?\.?|개|本|個|SETS?|세트|조|STK\.?|M|BOX(ES)?|PK|PKG)?$|^A\/?R$/i;
function splitFreeQty(line) {
  const no = line.match(/^\s*(\d{1,4})[.)]\s+/); let s = no ? line.slice(no[0].length) : line;
  const U = '(EA|PCS?\\.?|개|本|個|SETS?|세트|조|STK\\.?)';
  // 괄호 수량은 단위나 QTY가 있을 때만 ('NUTS (2)'처럼 너트 개수를 뜻하는 괄호는 건드리지 않음)
  let m = s.match(new RegExp(`^(.*?\\S)\\s*\\(\\s*(?:(?:QTY|Q'TY|수량)\\s*[:=]?\\s*(\\d[\\d,]*(?:\\.\\d+)?)\\s*${U}?|(\\d[\\d,]*(?:\\.\\d+)?)\\s*${U})\\s*\\)\\s*$`, 'i'));
  if (m) m = [m[0], m[1], m[2] || m[4], m[3] || m[5]];
  m = m || s.match(new RegExp(`^(.*?\\S)(?:\\s{2,}|\\s*\\|\\s*|\\s+(?:QTY|Q'TY|수량)\\s*[:=]?\\s*)(\\d[\\d,]*(?:\\.\\d+)?)\\s*${U}?\\s*$`, 'i'))
    || s.match(new RegExp(`^(.*\\S)\\s+(\\d[\\d,]*(?:\\.\\d+)?)\\s*${U}\\s*$`, 'i'));
  if (!m) return { no: no ? no[1] : '', text: s.trim(), qty: null };
  const text = m[1].replace(/\s*(?:[-X×*,;:|]|\bQTY)\s*$/i, '').trim();
  return { no: no ? no[1] : '', text, qty: m[2] + (m[3] ? ' ' + m[3] : '') };
}
const BOM_SPEC_HINT = /\b(A\d{3}M?|F\d{3,4}M?|B[78]M?|B16|L7M?|L43|2HM?|7M|NACE|MR0175|HDG|GALV\w*|ZINC|ZN-?NI|PTFE|XYLAN|FLUORO\w*|SS|STS|SUS|CR-?MO|ISO|ASTM|ASME|DIN|KS|JIS|IMPACT|CHARPY|MTR|EN\s?10204|3\.[12])\b|(?:^|\s)(4\.6|4\.8|5\.6|5\.8|6\.8|8\.8|10\.9|12\.9|A[24]-[78]0)(?:$|\s)|재질|도금|아연|스텐|충격|성적서/i;
function guessRoles(cells, n) {
  const roles = Array(n).fill(''), body = cells, col = i => body.map(r => r[i] || '');
  const avg = i => col(i).reduce((a, s) => a + s.length, 0) / body.length;
  const isQ = i => col(i).filter(s => QTY_RE.test(s)).length >= body.length * .7;
  let desc = 0; for (let i = 1; i < n; i++) if (avg(i) > avg(desc)) desc = i;
  roles[desc] = 'desc';
  const qs = [...Array(n).keys()].filter(i => i !== desc && isQ(i));
  if (qs.length) {
    const after = qs.filter(i => i > desc), qi = after.length ? after[0] : qs[qs.length - 1]; roles[qi] = 'qty';
    if (qs[0] === 0 && qi !== 0 && col(0).every((s, k) => +s === k + 1 || /^\d{1,4}$/.test(s))) roles[0] = 'no';
  }
  for (let i = 0; i < n; i++) if (!roles[i] && col(i).filter(s => /^(EA|PCS?|SETS?|개|本|個|세트|조|M)$/i.test(s)).length >= body.length * .6) { roles[i] = 'unit'; break; }
  // 머리글 없는 표: 재질·코팅·요구(B7M/2HM, NACE, HDG …)가 적힌 칸은 버리지 않고 함께 읽는다. 품번 같은 칸은 그대로 둔다
  for (let i = 0; i < n; i++) if (!roles[i]) { const v = col(i).filter(Boolean); if (v.length && v.filter(s => BOM_SPEC_HINT.test(s)).length >= v.length * .5) roles[i] = 'etc'; }
  return roles;
}
function bomRows(text, rolesIn) {
  const src = String(text || '').replace(/\r\n?/g, '\n').replace(/^﻿/, '');
  const lines = src.split('\n').filter(l => l.trim());
  if (!lines.length) return { rows: [], cols: [], roles: [], mode: 'empty', header: false };
  // 구분자: 탭 → 머리글이 있는 ; 또는 , → 줄마다 같은 수의 ; → 그 밖은 한 줄씩 적은 글
  let d = null;
  if (lines.filter(l => l.includes('\t')).length >= Math.max(1, lines.length / 2)) d = '\t';
  else for (const c of [';', ',']) { const h = lines[0].split(c); if (h.length > 1 && h.map(roleOf).filter(Boolean).length >= 2) { d = c; break; } }
  if (!d && lines.length >= 2) { const k = lines.map(l => (l.match(/;/g) || []).length); if (k[0] >= 1 && k.filter(x => x === k[0]).length >= lines.length * .8) d = ';'; }
  if (!d) {
    const rows = lines.map((l, i) => { const r = splitFreeQty(l); return { i, no: r.no || String(i + 1), pn: '', text: r.text, qty: r.qty, unit: '', src: l }; });
    return { rows, cols: [], roles: [], mode: 'text', header: false };
  }
  const cells = splitDelim(src, d) || lines.map(l => l.split(d).map(s => s.trim()));
  const n = Math.max(...cells.map(c => c.length));
  const hAt = cells.slice(0, 5).findIndex(r => r.map(roleOf).filter(Boolean).length >= 2), h0 = Math.max(0, hAt);
  const hdrRoles = cells[h0].map(roleOf), header = hAt >= 0;
  let roles;
  if (Array.isArray(rolesIn) && rolesIn.length) roles = Array.from({ length: n }, (_, i) => rolesIn[i] || '');
  else if (header) { roles = Array(n).fill(''); const seen = new Set(); hdrRoles.forEach((r, i) => { if (r && (BOM_MULTI.has(r) || !seen.has(r))) { roles[i] = r; seen.add(r); } }); }
  else roles = guessRoles(cells, n);
  const body = header ? cells.slice(h0 + 1) : cells;   // 머리글 위의 제목 줄은 품목이 아니다
  const idx = k => roles.map((r, i) => r === k ? i : -1).filter(i => i >= 0);
  const get = (r, k) => idx(k).map(i => (r[i] || '').trim()).filter(Boolean);
  const out = []; let prev = null;
  body.forEach((r, i) => {
    if (!r.some(s => String(s).trim())) return;
    const desc = get(r, 'desc').join(' '), type = get(r, 'type')[0] || '', size = get(r, 'size')[0] || '', len = get(r, 'len')[0] || '';
    const pn = get(r, 'pn').join(' / '), qRaw = get(r, 'qty')[0] || '', u = get(r, 'unit')[0] || '';
    const sizeLen = size ? (len ? `${size} X ${len}` : size) : len ? `X ${len}` : '';
    let text = [type, desc, sizeLen, ...get(r, 'mat'), ...get(r, 'fin'), ...get(r, 'etc')].filter(Boolean).join(' ');
    let filled = null;
    // 품명 칸이 빈 줄(엑셀 병합 셀): 품번도 비었거나 위 줄과 같으면 위 줄 사양을 이어 받고 표시한다. 빠뜨리지 않는다.
    if (!desc && !type && !size) {
      if (prev && prev.text && (!pn || pn === prev.pn)) { text = [prev.text, ...get(r, 'mat'), ...get(r, 'fin'), ...get(r, 'etc')].filter(Boolean).join(' '); filled = prev.no; }
      else if (pn) text = pn;
    }
    const no = get(r, 'no')[0] || String(i + 1);
    const row = { i, no, pn: desc || type || size || filled ? pn : '', text, qty: qRaw ? qRaw + (u && !/[A-Z가-힣本個]/i.test(qRaw) ? ' ' + u : '') : null, unit: u, src: r.join(' | '), filled };
    out.push(row);
    if (!filled) prev = row;
  });
  return { rows: out, cols: header ? cells[h0] : Array.from({ length: n }, (_, i) => `열 ${i + 1}`), sample: body[0] || [], roles, mode: d === '\t' ? 'tsv' : 'csv', delim: d, header };
}


export {bomRows,roleOf};
