// Reuse the homepage's tested table reader in the Worker; no browser or eval.
import {readFile,writeFile} from 'node:fs/promises';
const source=await readFile(new URL('../app/src/e9_rows.js',import.meta.url),'utf8');
const marker='// 테스트·포팅용 진입점';
if(!source.includes(marker))throw Error('BOM reader export boundary missing');
const result='// Generated by tools/build_bom_reader.mjs from app/src/e9_rows.js.\n'+source.slice(0,source.indexOf(marker))+'\nexport {bomRows,roleOf};\n';
const target=new URL('../worker/bom_rows.mjs',import.meta.url);
if(process.argv.includes('--check')){
  if(await readFile(target,'utf8')!==result)throw Error('Run node tools/build_bom_reader.mjs');
}else await writeFile(target,result);
